version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
