name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  go:
    uses: poseidon/.github/.github/workflows/golang-library.yaml@main
    with:
      setup_terraform: true
